App/models/books.py
from App.database import db
class Book(db.Model):
  book_id = db.Column(db.String, primary_key=True)
  Title = db.Column(db.String(100), nullable=False)
  Author = db.Column(db.String(100), nullable=False)
  Publication_Year = db.Column(db.Integer, nullable=False)
  status = db.Column(db.String(100), nullable=False)
  image = db.Column(db.String(100))
  
  def __init__(self, book_id,Title, Author, Publication_Year, status,image):
    self.book_id =book_id
    self.Title = Title
    self.Author = Author
    self.Publication_Year = Publication_Year
    self.status = status
    self.image = image
    

  def to_dict(self):
    return{
      'book_id': self.book_id,
      'Title': self.Title,
      'Author': self.Author,
      'Publication_Year': self.Publication_Year,
      'status': self.status,
      'image': self.image
    }
    

App/models/user.py
from werkzeug.security import check_password_hash, generate_password_hash
from App.database import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username =  db.Column(db.String, nullable=False, unique=True)
    password = db.Column(db.String(120), nullable=False)

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def get_json(self):
        return{
            'id': self.id,
            'username': self.username
        }

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password)
    
    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

App/controllers/books.py
from App.models.books import Book
from App.database import db

def create_book(ISBN, Title, Author, Publisher, Publication_Year, Price, status):
    book = Book(ISBN, Title, Author, Publisher, Publication_Year, Price, status, image)
    db.session.add(book)
    db.session.commit()
    return book    

def get_book(ISBN):
    book = Book.query.filter_by(ISBN=ISBN).first()
    return book   

def get_all_books():
    books = Book.query.all()
    return books

def update_book(ISBN, Title, Author, Publisher, Publication_Year, Price, status):
    book = Book.query.filter_by(ISBN=ISBN).first()
    book.Title = Title
    book.Author = Author
    book.Publisher = Publisher
    book.Publication_Year = Publication_Year
    book.Price = Price
    book.status = status
    db.session.commit()
    return book

def add_book_to_reading_list(book_id):
    # Find the book by book_id or create a new one if it doesn't exist
    book = Book.query.filter_by(id=book_id).first()
    if not book:
        # Create a new book entry with the status set to 'TBR'
        new_book = Book(id=book_id, status='TBR')
        db.session.add(new_book)
    else:
        # Update the status of the existing book to 'TBR'
        book.status = 'TBR'

    try:
        db.session.commit()
        return True
    except Exception as e:
        db.session.rollback()
        return False

def delete_book(ISBN):
    book = Book.query.filter_by(ISBN=ISBN).first()
    db.session.delete(book)
    db.session.commit()
    return book

App/controllers/user.py
from App.models import User
from App.database import db

def create_user(username, password):
    newuser = User(username=username, password=password)
    db.session.add(newuser)
    db.session.commit()
    return newuser

def get_user_by_username(username):
    return User.query.filter_by(username=username).first()

def get_user(id):
    return User.query.get(id)

def get_all_users():
    return User.query.all()

def get_all_users_json():
    users = User.query.all()
    if not users:
        return []
    users = [user.get_json() for user in users]
    return users

def update_user(id, username):
    user = get_user(id)
    if user:
        user.username = username
        db.session.add(user)
        return db.session.commit()
    return None
    

App/views/books.py
from flask import Blueprint, redirect, render_template, request, send_from_directory, jsonify, url_for,flash
from App.models.books import Book
from App.database import db



book_views = Blueprint('book_views', __name__, template_folder='../templates')


@book_views.route('/addBooktoTBR', methods=['POST'])
def add_book_to_reading_list():
    book_id = request.form['id']
    title = request.form['title']
    authors = request.form['authors']
    published_date = request.form['published_date']
    image = request.form['image']
    status = request.form['status']

    # Check if the book already exists
    book = Book.query.filter_by(book_id=book_id).first()
    if book:
        book.status = status
        flash(f"Book {title} status updated to {status}!")
    else:
        # Create a new book entry
        book = Book(book_id=book_id, Title=title, Author=authors, Publication_Year=published_date, status=status, image=image)
        db.session.add(book)
        flash(f"Book {title} added to {status}!", 'success')

    try:
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        flash(f"Failed to add/update book {title}. Error: {e}", 'danger')

    return redirect(url_for('index_views.index_page'))

 


@book_views.route('/show_tbr', methods=['GET'])
def show_tbr():
    tbr_books = Book.query.filter_by(status='TBR').all()
    return jsonify([{
        "book_id": book.book_id,
        "Title": book.Title,
        "Author": book.Author,
        "Publication_Year": book.Publication_Year,
        "status": book.status
    } for book in tbr_books])


@book_views.route('/show_favorites', methods=['GET'])
def show_favorites():
    tbr_books = Book.query.filter_by(status='favorites').all()
    return jsonify([{
        "book_id": book.book_id,
        "Title": book.Title,
        "Author": book.Author,
        "Publication_Year": book.Publication_Year,
        "status": book.status
    } for book in tbr_books])

@book_views.route('/books', methods=['GET'])
def list_books_by_status():
    favoriteBooks = Book.query.filter_by(status='favorites').all()
    tbrBooks = Book.query.filter_by(status='to read').all()
    readBooks = Book.query.filter_by(status='read').all()
    currentReadBooks = Book.query.filter_by(status='current read').all()

    return render_template('books.html', 
                           favoriteBooks=favoriteBooks, 
                           tbrBooks=tbrBooks, 
                           readBooks=readBooks, 
                           currentReadBooks=currentReadBooks)

App/views/user.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user as jwt_current_user

from.index import index_views

from App.controllers import (
    create_user,
    get_all_users,
    get_all_users_json,
    jwt_required
)

user_views = Blueprint('user_views', __name__, template_folder='../templates')

@user_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users)

@user_views.route('/users', methods=['POST'])
def create_user_action():
    data = request.form
    flash(f"User {data['username']} created!")
    create_user(data['username'], data['password'])
    return redirect(url_for('user_views.get_user_page'))

@user_views.route('/api/users', methods=['GET'])
def get_users_action():
    users = get_all_users_json()
    return jsonify(users)

@user_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
    data = request.json
    user = create_user(data['username'], data['password'])
    return jsonify({'message': f"user {user.username} created with id {user.id}"})

@user_views.route('/static/users', methods=['GET'])
def static_user_page():
  return send_from_directory('static', 'static-user.html')

App/templates/401.html
{% extends "layout.html" %}
{% block title %}Not Authorized{% endblock %}
{% block page %}Not Auhtorized{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <div class="card-content">
                <h1>401 - Not Authorized</h1>
                <p>You do not have permission to access this resource. Please check your credentials and try again.</p>
                <p>{{error}}</p>
            </div>
            <div class="card-action">
                <a href="/" class="waves-effect waves-light btn">Go Home</a>
                <a href="javascript:history.back()" class="waves-effect waves-light btn">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/books.html
{% extends "layout.html" %}

{% block title %}BookMap{% endblock %}
{% block page %}BookMap{% endblock %}

{% block content %}

<h1>Favorites</h1>
<div class="row">
    {% if favoriteBooks %}
        {% for book in favoriteBooks %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ book.image }}" class="card-img-top" alt="{{ book.Title }} cover">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.Title }}</h5>
                        <p class="card-text">{{ book.Author }}</p>
                        <p class="card-text">{{ book.Publication_Year }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No favorite books found.</p>
    {% endif %}
</div>

<h1>To Be Read</h1>
<div class="row">
    {% if tbrBooks %}
        {% for book in tbrBooks %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ book.image }}" class="card-img-top" alt="{{ book.Title }} cover">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.Title }}</h5>
                        <p class="card-text">{{ book.Author }}</p>
                        <p class="card-text">{{ book.Publication_Year }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No books to be read found.</p>
    {% endif %}
</div>

<h1>Read</h1>
<div class="row">
    {% if readBooks %}
        {% for book in readBooks %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ book.image }}" class="card-img-top" alt="{{ book.Title }} cover">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.Title }}</h5>
                        <p class="card-text">{{ book.Author }}</p>
                        <p class="card-text">{{ book.Publication_Year }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No read books found.</p>
    {% endif %}
</div>

<h1>Current Read</h1>
<div class="row">
    {% if currentReadBooks %}
        {% for book in currentReadBooks %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ book.image }}" class="card-img-top" alt="{{ book.Title }} cover">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.Title }}</h5>
                        <p class="card-text">{{ book.Author }}</p>
                        <p class="card-text">{{ book.Publication_Year }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No current-read books found.</p>
    {% endif %}
</div>

{% endblock %}

App/templates/index.html
    {% extends "layout.html" %}

    {% block title %}BookMap{% endblock %}
    {% block page %}BookMap{% endblock %}

    {% block content %}
    <h2>Enter your current read</h2>
    <form class="form-inline mb-4" action="/search" method="get">
        <input id="books" class="form-control mr-sm-2" type="search" name="q" placeholder="Enter book name" aria-label="Search" required>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Enter book</button>
    </form>


    <h1>Top Books</h1>
    <div class="row">
        {% for book in books %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    {% if book.volumeInfo.imageLinks and book.volumeInfo.imageLinks.thumbnail %}
                        <img src="{{ book.volumeInfo.imageLinks.thumbnail }}" class="card-img-top" alt="{{ book.volumeInfo.title }} cover">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ book.volumeInfo.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ book.volumeInfo.authors | join(', ') if book.volumeInfo.authors else 'Unknown' }}</h6>
                        <p class="card-text">{{ book.volumeInfo.publishedDate }}</p>
                        <div class="card-action">
                            <form action="{{ url_for('book_views.add_book_to_reading_list') }}" method="POST">
                                <input type="hidden" name="id" value="{{ book.id }}">
                                <input type="hidden" name="title" value="{{ book.volumeInfo.title }}">
                                <input type="hidden" name="authors" value="{{ book.volumeInfo.authors | join(', ') if book.volumeInfo.authors else 'Unknown' }}">
                                <input type="hidden" name="published_date" value="{{ book.volumeInfo.publishedDate }}">
                                <input type="hidden" name="image" value="{{ book.volumeInfo.imageLinks.thumbnail if book.volumeInfo.imageLinks and book.volumeInfo.imageLinks.thumbnail else 'https://via.placeholder.com/150' }}">

                                <div class="form-group">
                                    <label for="status">Select Status:</label>
                                    <select name="status" id="status" class="form-control">
                                        <option value="favorites">Favorites</option>
                                        <option value="to read">To Read</option>
                                        <option value="read">Read</option>
                                        <option value="current read">Currently Reading</option>
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-primary">Add To Reading List</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <script>
    (function() {
        var allbooks = [
            {% for book in books %}
                "{{ book.volumeInfo.title }}",
            {% endfor %}
        ];
        $("#books").autocomplete({
            source: allbooks
        });
    })();
    </script>
    {% endblock %}

App/templates/layout.html
<!doctype html>
<html>
  <head>
  
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
     <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %}</title>

  </head>
  <body>
    
      <nav class="purple">
          <div class="nav-wrapper">
              <a href="#!" class="brand-logo center">{% block page %}{% endblock %}</a>
              <ul id="nav-mobile" class="left">
                  <li><a href="/">Home</a></li>
                  <li><a href="/users">Read</a></li>

                    <li><a href="/books">Books</a></li>
                
                  <li><a href="/static/users"> Book Club</a></li>
              </ul>
              {% if is_authenticated %}
              <ul id="nav-mobile" class="right">
                <li><a href="/logout">Logout</a></li>
              </ul>
              {% else %}
              <form class="right navbar-form" method="POST" action="/login" style="display: flex; flex-wrap: nowrap; align-items: center; margin-right: 10px;">
                  <div class="input-field" style="margin-right: 10px;">
                      <input placeholder="username" value="bob" name="username" type="text" class="validate" required>
                      <label for="username">username</label>
                  </div>
                  <div class="input-field" style="margin-right: 10px;">
                      <input placeholder="password"value="bobpass" name="password" type="password" class="validate" required>
                      <label for="password">Password</label>
                  </div>
                  <button type="submit" class="btn waves-effect waves-light">Login</button>
              </form>
              {% endif %}
              
          </div>
      </nav>
      <style>
          .navbar-form label {
              color: white !important;
          }
      </style>

    <div class="container" id="content">{% block content %}{% endblock %}</div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
       M.AutoInit();

        {% with messages = get_flashed_messages() %}
          {% if messages %}
              {% for message in messages %}
              M.toast({html: '{{message}}'})
              {% endfor %}
          {% endif %}
        {% endwith %}
       
    </script>
  </body>
</html>

App/templates/message.html
{% extends "layout.html" %}
{% block title %}{{title}}{% endblock %}
{% block page %}{{title}}{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <p>{{message}}</p>
        </div>
    </div>
</div>
{% endblock %}

App/templates/users.html
{% extends "layout.html" %}
{% block title %}App Users{% endblock %}
{% block page %}App Users{% endblock %}

{{ super() }}

{% block content %}
    <div class="row">
        <p>
            This is table is renderd on the Server. Flask gets the data from the database and uses jinja templates to dyanmically render this page when a request is sent to <a href="/users">/users</a>.
        </p>
    </div>

    <div class="row">
      <form class="col s12" method="POST" action="/users">
        
        <div class="row">
          <div class="input-field col s6">
            <input placeholder="Username" name="username" type="text" class="validate">
            <label for="username">Username</label>
          </div>
          <div class="input-field col s6">
            <input placeholder="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
        </div>
      
        <div class="row">
          <div class="input-field col s12">
            <button class="btn waves-effect waves-light right purple" type="submit" name="action">Submit</button>
          </div>
        </div> 

      </form>
    </div>

    <div class="row">
      <table>
        <thead>
          <tr>
            <th>Id</th><th>Username</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.username}}</td>
            </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>

{% endblock %}